### ISSUE TITLE
Helpful reference to build an API using Lambda

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/ARGO-API#1]
@rewajkale - check out these instructions to quickly create an API using Lambda. 
https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/tree/master/AWS_API_Gateway

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by christophertull** [comment]
This is epic!

**Comment by rewajkale** [comment]
@vr00n What was purpose would I need Stackedit.io
Will you please elaborate more on it

**Comment by vr00n** [comment]
@rewajkale [Stackedit.io](https://stackedit.io/) is just a helpful resource to write markdown better. 

We try our best to ensure that when you create an issue, it contains as much information as possible (including screenshots) and properly formatted to ensure that issue communication is as efficient as possible and avoid miscommunication and back-n-forth.

Issues(like in this case) can also be used to get a team member's attention to some very useful resource that will meaningfully help with project delivery.

I felt that the link covers most of the elements in terms of:

1. Creating a Lambda
2. Creating an API endpoint that triggers the Lambda function

....which are the initial key steps for ARGO-API project before approaching the monetization concepts.

You may close this issue after you + @ankpatil18 have reviewed.
