### ISSUE TITLE
Please read: Sell Your API Gateway API through AWS Marketplace

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/ARGO-API#2]
@rewajkale here is another resource to refer re: API monetization. 

https://docs.aws.amazon.com/apigateway/latest/developerguide/sell-api-as-saas-on-aws-marketplace.html

Again, the goal is to create a simple API/Lambda that just adds any 2 numbers and list this API through the AWS marketplace. 

Once we do that, we would like to know how to handle key management and payment.

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by rewajkale** [comment]
Created a function on AWS Lambda and triggered it using API Gateway. Tested it. Works well. Coded in node.js as requested by @vr00n 
Going to work on how to sell API through AWS Marketplace

**Comment by rewajkale** [comment]
Requested for a new account for AWS marketplace and received a notification saying: wait for 48 hours till someone from AWS marketplace team contacts for next steps.
So have to wait till the request is approved

**Comment by rewajkale** [comment]
The AWS representative replied with an email saying:
_https://www.fcny.org/fcny/about/ncci/, is missing some information. Specifically, we ask that sellers provide information regarding their company & product, and have a defined support process and organizing, like documentation, support package or FAQ's.

Also, the product description for your company is currently listed as "add two numbers". Can you please provide us with further information on your product?

Please let us know when these issues have been addressed and we can move forward with the seller registration process._

Working on this part @vr00n

**Comment by vr00n** [comment]
Hi @rewajkale @ankpatil18 - please share the code for the api as well details for API gateway so that we can replicate / test  on the official  ARGO account.

Can someone please update the readme for this repo?

**Comment by rewajkale** [comment]
Uploaded the code and updated the Readme @vr00n

**Comment by vr00n** [comment]
I have created a new AWS account and sent you details to access. Please use this and list on the marketplace.
