### ISSUE TITLE
Initial Use Case

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/ARGO-API#3]
Hi team I wanted to start a simple thread to discuss and prioritize the initial data stream for this exciting (and important!) experiment. Some ideas:

- Integrating water rights information. Note this would require a new parser. See here for a nice previous visualization project that may be worth [building off of this visualization. ](http://ca.statewater.org/content/water-rights) [Note we may not have a good niche though](https://www.newsdeeply.com/water/community/2017/04/11/the-chore-of-understanding-water-rights-just-got-a-little-easier)
- API for reservoir levels. Note nice thing here is we have a dedicated lab resource working on updating that already so can focus on building the API. One idea that may or may not make sense would be to sync up the reservoir levels with CIMIS and future climate to provide enriched data as a value add for the API. 
- Not sure if it'd be easy technically though maybe something related to OWRS? 

Curious to everyone's ideas on how to proceed and optimal vector forward to maximize this experiment.

CC @vr00n @christophertull @dmarulli

**Comment by vr00n** [comment]
@patwater i'd prefer if Rewa first delivers on simple and reproducible generic blueprint. 

You may want to discuss amongst yourselves outside of this project what it can apply to after we are able to deliver this.

Our goal here is to ensure that there is a simple and reproducible way to stand up an API that can be monetizable. 

This project aims to simply add 2 numbers using a Lambda and the remainder of the work is to figure out how the API keys are produced and managed and the various ways to connect the API to FCNY compatible payment processors.

Domain-specific use cases are out of scope until we deliver on that. 

Im closing this issue as is out of scope for this particular engagement with Rewa. Thanks

**Comment by rewajkale** [comment]
@vr00n will you please explain the project in short? So that I would know where to start working on it. Thank you.
