### ISSUE TITLE
Invoking the API with the key

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/ARGO-API#5]
@ankpatil18 I am trying to invoke this API using the key you created. 
I am getting `{"message":"Forbidden"}`

I followed this https://stackoverflow.com/questions/39061041/using-an-api-key-in-amazon-api-gateway and tried

`curl -X POST -H "x-api-key: <CUSTOMER1KEY>" -H "Content-Type: application/json" https://pdvvb0q0x6.execute-api.us-east-2.amazonaws.com/addNumbers?number1=1&number2=2`

Can you please check to see how I can invoke this API successfully?

Thanks!

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by ankpatil18** [comment]
@vr00n 

Yes, I made some changes now its working: 

this is the curl I am using:

`curl -H "x-api-key: Iw1iWQ0ikcadsz70i5JQ7agTRJYrqtpi4wKcj0Wj" -H "Content-Type: application/json" "https://pdvvb0q0x6.execute-api.us-east-2.amazonaws.com/prod/addNumbers?number1=10&number2=70"`

**Comment by christophertull** [comment]
[This is 💯 ](https://pdvvb0q0x6.execute-api.us-east-2.amazonaws.com/prod/addNumbers?number1=1&number2=99)

**Comment by christophertull** [comment]
Seems to  be working without an API key?

**Comment by vr00n** [comment]
Agreed while the API itself is working, it is also working without the API key. 

@ankpatil18 @rewajkale could you please investigate on why this is the case.

Also would appreciate some updated documentation. 

Great work so far! Keep it up!

**Comment by ankpatil18** [comment]
@vr00n  : Investigated, now its only working with key.

Please try it and let me know,  will update the docs, can you post next requirement?

**Comment by rewajkale** [comment]
Yes I can see it is working @ankpatil18 what change you did? Will you please tell me?

**Comment by rewajkale** [comment]
Okay I tried creating another Usage Plan and API key and then tried deploying the application again. I observed that any change made to the Usage plan needs a redeployment of application. So when @ankpatil18 redeployed the application, it worked well. @vr00n the requirement looks like completed

**Comment by christophertull** [comment]
I can also confirm that I am now getting "forbidden" message when accessing without API key.

**Comment by vr00n** [comment]
AMAZING WORK! I will close this issue.

@rewajkale @ankpatil18 closing this issue and yes I believe the requirements are now complete. 

Great team work!
